import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex">
          <div className="w-3/12 min-h-screen p-10">
            <h1 className="text-2xl font-sans font-semibold text-center">
              POKEDEX
            </h1>
            <div className="mt-10">
              <Link href="/">
                <h1 className="text-2xl font-sans font-semibold text-center my-5">
                  Home
                </h1>
              </Link>
              <Link href="/create-pokemon">
                <h1 className="text-2xl font-sans font-semibold text-center my-5">
                  Add
                </h1>
              </Link>
              <Link href="/fire">
                <h1 className="text-2xl font-sans font-semibold text-center my-5">
                  Fire
                </h1>
              </Link>
              <Link href="/water">
                <h1 className="text-2xl font-sans font-semibold text-center my-5">
                  Water
                </h1>
              </Link>
              <Link href="/grass">
                <h1 className="text-2xl font-sans font-semibold text-center my-5">
                  Grass
                </h1>
              </Link>
            </div>
          </div>
          <div className="w-9/12 min-h-screen bg-slate-200 p-10">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
